"""Adds Trip and Reservation models

Revision ID: 54a25f8d25cc
Revises: 
Create Date: 2024-10-17 15:28:24.312497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54a25f8d25cc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('continent', sa.Enum('AFRICA', 'ANTARCTICA', 'ASIA', 'AUSTRALASIA', 'EUROPE', 'NORTH_AMERICA', 'SOUTH_AMERICA', name='continent'), nullable=False),
    sa.Column('about', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('weeks', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('reservation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservation')
    op.drop_table('trip')
    # ### end Alembic commands ###
